version: '3.8'

services:
  helloworld-app:
    image: helloworld-app
    build: .
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    networks:
      - webnet

  nginx:
    image: nginx:1.23.4
    volumes:
      - ./nginx/helloworld.conf:/etc/nginx/conf.d/helloworld.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - helloworld-app
    networks:
      - webnet

networks:
  webnet:
